import { useState } from 'react';
import { Download, FileText, Printer } from 'lucide-react';
import { useProjectData } from '@/hooks/useProjectData';
import { calculatePortfolioSummary, calculateSegmentMetrics } from '@/lib/calculations';
import { formatCurrency, formatPercent } from '@/lib/formatters';

function generateCsvContent(projects: import('@/lib/types').ProjectRecord[]): string {
  const headers = [
    'Project Name', 'Customer', 'Division', 'Market Segment', 'Year',
    'Original Contract Value', 'Revised Contract Value', 'Final Contract Value',
    'Original Est. Cost', 'Final Cost', 'Final Profit', 'Profit Margin (%)',
    'Gain/Fade ($)', 'Gain/Fade', 'Original Est. Labor Hours', 'Final Labor Hours',
  ];
  const rows = projects.map((p) => [
    `"${p.projectName}"`, `"${p.customerName}"`, p.division, p.marketSegment, p.yearCompleted,
    p.originalContractValue.toFixed(2), p.revisedContractValue.toFixed(2), p.finalContractValue.toFixed(2),
    p.originalEstimatedCost.toFixed(2), p.finalCost.toFixed(2), p.finalProfit.toFixed(2),
    (p.finalGrossProfitMargin * 100).toFixed(2),
    p.gainFadeOrgFinalDollars.toFixed(2), p.overallGainFade,
    p.originalEstimatedLaborHours.toFixed(0), p.finalLaborHours.toFixed(0),
  ]);
  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
}

function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

function generateTextReport(projects: import('@/lib/types').ProjectRecord[]): string {
  const summary = calculatePortfolioSummary(projects);
  const segments = calculateSegmentMetrics(projects);
  const fadedProjects = projects.filter((p) => p.overallGainFade === 'Fade');
  const fadeDollars = fadedProjects.reduce((s, p) => s + Math.abs(p.gainFadeOrgFinalDollars), 0);

  let report = `PORTFOLIO PERFORMANCE REPORT
Generated: ${new Date().toLocaleDateString()}
${'='.repeat(60)}

EXECUTIVE SUMMARY
${'-'.repeat(40)}
Total Projects:        ${summary.totalProjects}
Total Revenue:         ${formatCurrency(summary.totalRevenue)}
Avg Contract Value:    ${formatCurrency(summary.averageContractValue)}
Total Profit:          ${formatCurrency(summary.totalProfit)}
Avg Profit Margin:     ${formatPercent(summary.averageProfitMargin)}
Gain Rate:             ${formatPercent(summary.gainRate)} (${summary.gainCount} gain / ${summary.fadeCount} fade)
Net Gain/Fade:         ${formatCurrency(summary.totalGainFadeDollars)}
Divisions:             ${summary.divisions.join(', ')}
Market Segments:       ${summary.marketSegments.join(', ')}

`;

  if (fadedProjects.length > 0) {
    report += `RISK EXPOSURE
${'-'.repeat(40)}
Total Fade Exposure:   ${formatCurrency(fadeDollars)}
Faded Projects:        ${fadedProjects.length}
Avg Fade per Project:  ${formatCurrency(fadeDollars / fadedProjects.length)}

`;
  }

  report += `MARKET SEGMENT PERFORMANCE
${'-'.repeat(40)}
${'Segment'.padEnd(15)} ${'Projects'.padStart(10)} ${'Revenue'.padStart(14)} ${'Avg Margin'.padStart(12)} ${'Net G/F'.padStart(14)}
`;
  for (const seg of segments) {
    report += `${seg.segment.padEnd(15)} ${String(seg.projectCount).padStart(10)} ${formatCurrency(seg.totalRevenue).padStart(14)} ${formatPercent(seg.averageMargin).padStart(12)} ${formatCurrency(seg.totalGainFade).padStart(14)}\n`;
  }

  report += `\nPROJECT DETAILS
${'-'.repeat(40)}
${'Project'.padEnd(25)} ${'Value'.padStart(14)} ${'Margin'.padStart(10)} ${'G/F $'.padStart(14)} ${'Status'.padStart(8)}
`;
  const sorted = [...projects].sort((a, b) => b.finalContractValue - a.finalContractValue);
  for (const p of sorted) {
    report += `${p.projectName.substring(0, 24).padEnd(25)} ${formatCurrency(p.finalContractValue).padStart(14)} ${formatPercent(p.finalGrossProfitMargin).padStart(10)} ${formatCurrency(p.gainFadeOrgFinalDollars).padStart(14)} ${p.overallGainFade.padStart(8)}\n`;
  }

  report += `\n${'='.repeat(60)}\nGenerated by Project Performance Intelligence — Powered by Automized (automized.com)\n`;

  return report;
}

export function ExportButton() {
  const [isOpen, setIsOpen] = useState(false);
  const { filteredProjects } = useProjectData();

  if (filteredProjects.length === 0) return null;

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 rounded-lg border border-border px-3 py-1.5 text-sm text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors"
      >
        <Download className="h-4 w-4" />
        <span className="hidden sm:inline">Export</span>
      </button>

      {isOpen && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
          <div className="absolute right-0 top-full mt-2 w-64 rounded-xl border border-border bg-card p-2 shadow-xl z-50">
            <button
              onClick={() => {
                downloadBlob(generateCsvContent(filteredProjects), 'portfolio-data.csv', 'text/csv');
                setIsOpen(false);
              }}
              className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm hover:bg-accent transition-colors"
            >
              <FileText className="h-4 w-4 text-primary" />
              <div className="text-left">
                <p className="font-medium text-foreground">Export as CSV</p>
                <p className="text-xs text-muted-foreground">Raw data for Excel/Sheets</p>
              </div>
            </button>
            <button
              onClick={() => {
                downloadBlob(generateTextReport(filteredProjects), 'portfolio-report.txt', 'text/plain');
                setIsOpen(false);
              }}
              className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm hover:bg-accent transition-colors"
            >
              <Download className="h-4 w-4 text-primary" />
              <div className="text-left">
                <p className="font-medium text-foreground">Executive Summary Report</p>
                <p className="text-xs text-muted-foreground">Text report with key metrics</p>
              </div>
            </button>
            <button
              onClick={() => {
                window.print();
                setIsOpen(false);
              }}
              className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm hover:bg-accent transition-colors"
            >
              <Printer className="h-4 w-4 text-primary" />
              <div className="text-left">
                <p className="font-medium text-foreground">Print Dashboard</p>
                <p className="text-xs text-muted-foreground">Print current view</p>
              </div>
            </button>
          </div>
        </>
      )}
    </div>
  );
}
